# Generated by Django 2.0.6 on 2018-06-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveSmallIntegerField(help_text='order to display entries')),
                ('description', models.TextField(help_text='short description of an aspect of the position')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.PositiveSmallIntegerField(verbose_name='Zip Code')),
                ('summary', models.TextField(help_text='One or two paragraphs summarizing your goals, history, and skills.')),
                ('hook', models.TextField(help_text='short blurb or tag line')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='One or two word skill name. Try to reuse first.', max_length=100, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('org_description', models.CharField(max_length=200, verbose_name='Organization Description')),
                ('org_city', models.CharField(max_length=100, verbose_name='Organization City')),
                ('org_state', models.CharField(max_length=100, verbose_name='Organization State')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('current', models.BooleanField(default=False, verbose_name='Current Position')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_build.Resume')),
            ],
        ),
        migrations.AddField(
            model_name='skills',
            name='positions',
            field=models.ManyToManyField(to='cv_build.WorkHistory'),
        ),
        migrations.AddField(
            model_name='positiondetails',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv_build.WorkHistory'),
        ),
    ]
