# Generated by Django 2.0.6 on 2018-06-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_build', '0002_auto_20180610_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
