# Generated by Django 2.0.6 on 2018-06-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_build', '0003_auto_20180615_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='url_name',
            field=models.CharField(default='Zach_Sizemore', help_text='String to display in URL. Must be unique', max_length=30, verbose_name='URL Name'),
            preserve_default=False,
        ),
    ]
