# Generated by Django 2.0.6 on 2018-06-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_build', '0004_resume_url_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positiondetails',
            options={'ordering': ['-sort']},
        ),
        migrations.AddField(
            model_name='workhistory',
            name='hook',
            field=models.TextField(default='', help_text='short description of position'),
            preserve_default=False,
        ),
    ]
